
title: 'RedTeam Rat'
email: rat@redteam.ng
description: >- # this means to ignore newlines until "baseurl:"
  Penetration Tester And Redteamer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "ratilovich"
#google_analytics: UA-NNNNNNNN-N
#listen_for_clients_preferred_style: true # true or false (default)

style: hacker


plugins:
  - jekyll-seo-tag
  - jekyll-feed

header_pages:
  - index.md
  - brainbox.md
  - resume.md

footer: 'follow me on <a href="https://twitter.com/ratilovich">twitter</a> '


# Build settings
markdown: kramdown
