
title: 'RedTeam Rat'
email: rat@redteam.ng
description: >- # this means to ignore newlines until "baseurl:"
  Penetration Tester And Redteamer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "ratilovich"
#google_analytics: UA-NNNNNNNN-N
#listen_for_clients_preferred_style: true # true or false (default)

style: hacker


plugins:
  - jekyll-seo-tag
 # - jekyll-responsive-image
#- jekyll-feed

header_pages:
  - index.md
  - brainbox.md
  - resume.md

footer: '<a href="https://twitter.com/ratilovich">Twitter</a> '


# Build settings
markdown: kramdown



#custom code for responsive image
#https://github.com/wildlyinaccurate/jekyll-responsive-image
# responsive_image:
#   template: _includes/responsive-image.html
#   sizes:
#     - width: 320
#     - width: 480
#     - width: 800